In [104]:
import sklearn
from matplotlib import pyplot as plt
import pandas as pd
import numpy as np

In [105]:
data=pd.read_csv("CarPrice_Assignment.csv")
data

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [106]:
d1=pd.get_dummies(data["CarName"])
d2=pd.get_dummies(data["fueltype"])
d3=pd.get_dummies(data["doornumber"])
d4=pd.get_dummies(data["carbody"])
d5=pd.get_dummies(data["enginetype"])
data=pd.concat([data,d1,d2,d3,d4,d5],axis=1)
data

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,hatchback,sedan,wagon,dohc,dohcv,l,ohc,ohcf,ohcv,rotor
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,0,0,0,1,0,0,0,0,0,0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,0,0,0,1,0,0,0,0,0,0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,1,0,0,0,0,0,0,0,1,0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,0,1,0,0,0,0,1,0,0,0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,0,1,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,0,1,0,0,0,0,1,0,0,0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,0,1,0,0,0,0,1,0,0,0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,0,1,0,0,0,0,0,0,1,0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,0,1,0,0,0,0,1,0,0,0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,0,1,0,0,0,0,1,0,0,0

In [107]:
data.drop(["CarName","fueltype","doornumber","carbody","enginetype"],axis=1,inplace=True)
data

,car_ID,symboling,aspiration,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,curbweight,...,hatchback,sedan,wagon,dohc,dohcv,l,ohc,ohcf,ohcv,rotor
0,1,3,std,rwd,front,88.6,168.8,64.1,48.8,2548,...,0,0,0,1,0,0,0,0,0,0
1,2,3,std,rwd,front,88.6,168.8,64.1,48.8,2548,...,0,0,0,1,0,0,0,0,0,0
2,3,1,std,rwd,front,94.5,171.2,65.5,52.4,2823,...,1,0,0,0,0,0,0,0,1,0
3,4,2,std,fwd,front,99.8,176.6,66.2,54.3,2337,...,0,1,0,0,0,0,1,0,0,0
4,5,2,std,4wd,front,99.4,176.6,66.4,54.3,2824,...,0,1,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,std,rwd,front,109.1,188.8,68.9,55.5,2952,...,0,1,0,0,0,0,1,0,0,0
201,202,-1,turbo,rwd,front,109.1,188.8,68.8,55.5,3049,...,0,1,0,0,0,0,1,0,0,0
202,203,-1,std,rwd,front,109.1,188.8,68.9,55.5,3012,...,0,1,0,0,0,0,0,0,1,0
203,204,-1,turbo,rwd,front,109.1,188.8,68.9,55.5,3217,...,0,1,0,0,0,0,1,0,0,0
204,205,-1,turbo,rwd,front,109.1,188.8,68.9,55.5,3062,...,0,1,0,0,0,0,1,0,0,0

In [108]:
data.drop(["car_ID","symboling","aspiration","drivewheel","enginelocation","wheelbase","carlength","carwidth","carheight","curbweight","cylindernumber","enginesize","fuelsystem","boreratio","stroke","compressionratio","horsepower","peakrpm","citympg","highwaympg"],axis=1,inplace=True)

In [109]:
data

,price,Nissan versa,alfa-romero Quadrifoglio,alfa-romero giulia,alfa-romero stelvio,audi 100 ls,audi 100ls,audi 4000,audi 5000,audi 5000s (diesel),...,hatchback,sedan,wagon,dohc,dohcv,l,ohc,ohcf,ohcv,rotor
0,13495.0,0,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1,16500.0,0,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2,16500.0,0,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
3,13950.0,0,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
4,17450.0,0,0,0,0,0,1,0,0,0,...,0,1,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,16845.0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
201,19045.0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
202,21485.0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
203,22470.0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
204,22625.0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0

In [110]:
x=data.drop(["price"],axis=1)
y=data["price"]

In [111]:
 # from sklearn.model_selection import train_test_split
 # xtrain,ytrain,xtest,ytest=train_test_split(x,y,train_size=.8,random_state=1)

In [112]:
from sklearn.linear_model import LinearRegression

In [113]:
model=LinearRegression()

In [114]:
model.fit(x,y)

LinearRegression()

In [115]:
model.score(x,y)

-2.4364069324343016